# Generated by Django 4.0.5 on 2022-06-30 13:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='Lead',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('fname', models.CharField(max_length=255)),
				('lname', models.CharField(max_length=255)),
				('email', models.EmailField(max_length=254)),
				('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
		),
	]
