# Generated by Django 4.0.5 on 2022-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
